#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/sbin/wrtbwmon-ng"

    # respawn automatically if something died, be careful if you have an alternative process supervisor
    # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/wrtbwmon-ng.conf # /etc/init.d/wrtbwmon-ng reload will restart the daemon if these files have changed
    procd_set_param pidfile /var/run/wrtbwmon.pid # write a pid file on instance start and remove it on stop
    procd_close_instance
}